### ISSUE TITLE
Cannot build gmic-qt 3.2.0 with cmake

### ISSUE THREAD

**Issue by NinjaTrappeur** [c-koi/gmic-qt#171]
Hello :)

We've been trying to bump gmic-lib from 3.1.6 to gmic-lib 3.2.0 in NixOS (a linux distribution).

The build sadly fails on the `FilterSyncRunner` file:

```
FAILED: CMakeFiles/gmic_qt.dir/src/FilterSyncRunner.cpp.o 
/nix/store/iiq295j1z4q1sxmdbrl2j8ma3l5ns4wr-gcc-wrapper-11.3.0/bin/g++ -DGMIC_HOST=standalone -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_WIDGETS_LIB -D_IS_LINUX_ -D_IS_UNIX_ -Dcimg_appname=\"gmic\" -Dcimg_display=1 -Dcimg_use_abort -Dcimg_use_cpp11=1 -Dcimg_use_curl -Dcimg_use_fftw3 -Dcimg_use_openmp -Dcimg_use_png -Dcimg_use_vt100 -Dcimg_use_zlib -Dgmic_community -Dgmic_gui -Dgmic_is_parallel -I/build/source/build -I/build/source -I/build/source/build/gmic_qt_autogen/include -I/build/source/src -isystem /nix/store/03svkk8l8dfcbabfl9637krwdkhqvyna-qtbase-5.15.8-dev/include/QtCore -isystem /nix/store/03svkk8l8dfcbabfl9637krwdkhqvyna-qtbase-5.15.8-dev/./mkspecs/linux-g++ -isystem /nix/store/03svkk8l8dfcbabfl9637krwdkhqvyna-qtbase-5.15.8-dev/include/QtWidgets -isystem /nix/store/03svkk8l8dfcbabfl9637krwdkhqvyna-qtbase-5.15.8-dev/include/QtGui -isystem /nix/store/03svkk8l8dfcbabfl9637krwdkhqvyna-qtbase-5.15.8-dev/include/QtNetwork -DNDEBUG -Ofast -fopenmp -fPIC -std=gnu++11 -MD -MT CMakeFiles/gmic_qt.dir/src/FilterSyncRunner.cpp.o -MF CMakeFiles/gmic_qt.dir/src/FilterSyncRunner.cpp.o.d -o CMakeFiles/gmic_qt.dir/src/FilterSyncRunner.cpp.o -c /build/source/src/FilterSyncRunner.cpp
/build/source/src/FilterSyncRunner.cpp: In member function 'void GmicQt::FilterSyncRunner::swapImages(gmic_library::gmic_list<float>&)':
/build/source/src/FilterSyncRunner.cpp:77:12: error: 'struct gmic_library::gmic_list<float>' has no member named 'swap'
   77 |   _images->swap(images);
      |            ^~~~
/build/source/src/FilterSyncRunner.cpp: In member function 'void GmicQt::FilterSyncRunner::run()':
/build/source/src/FilterSyncRunner.cpp:160:69: error: invalid user-defined conversion from 'gmic_library::gmic_image<char>' to 'char' [-fpermissive]
  160 |     gmicInstance.set_variable("_persistent", PersistentMemory::image());
      |                                              ~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /build/source/src/FilterSyncRunner.cpp:35:
/nix/store/hdjr32qnmgqmysllvq6v5ds09mhvz5ja-gmic-3.2.0-dev/include/gmic.h:118:5: note: candidate is: 'gmic_library::gmic_image<T>::operator T*() [with T = char]' (near match)
  118 |     operator T*() {
      |     ^~~~~~~~
/nix/store/hdjr32qnmgqmysllvq6v5ds09mhvz5ja-gmic-3.2.0-dev/include/gmic.h:118:5: note:   no known conversion from 'char*' to 'char'
In file included from /build/source/src/FilterSyncRunner.cpp:35:
/nix/store/hdjr32qnmgqmysllvq6v5ds09mhvz5ja-gmic-3.2.0-dev/include/gmic.h:389:63: note:   initializing argument 2 of 'const char* gmic::set_variable(const char*, char, const char*, double, const unsigned int*)'
  389 |   const char *set_variable(const char *const name, const char operation='=', const char *const value=0,
      |                                                    ~~~~~~~~~~~^~~~~~~~~~~~~
/build/source/src/FilterSyncRunner.cpp:165:46: error: 'struct gmic_library::gmic_image<char>' has no member named 'move_to'
  165 |     gmicInstance.get_variable("_persistent").move_to(*_persistentMemoryOuptut);
      |                                              ^~~~~~~
/build/source/src/FilterSyncRunner.cpp:167:20: error: no matching function for call to 'gmic_library::gmic_list<float>::assign()'
  167 |     _images->assign();
      |     ~~~~~~~~~~~~~~~^~
In file included from /build/source/src/FilterSyncRunner.cpp:35:
/nix/store/hdjr32qnmgqmysllvq6v5ds09mhvz5ja-gmic-3.2.0-dev/include/gmic.h:151:19: note: candidate: 'gmic_library::gmic_list<T>& gmic_library::gmic_list<T>::assign(unsigned int) [with T = float]'
  151 |     gmic_list<T>& assign(const unsigned int n);
      |                   ^~~~~~
/nix/store/hdjr32qnmgqmysllvq6v5ds09mhvz5ja-gmic-3.2.0-dev/include/gmic.h:151:19: note:   candidate expects 1 argument, 0 provided
/build/source/src/FilterSyncRunner.cpp:168:24: error: no matching function for call to 'gmic_library::gmic_list<char>::assign()'
  168 |     _imageNames->assign();
      |     ~~~~~~~~~~~~~~~~~~~^~
In file included from /build/source/src/FilterSyncRunner.cpp:35:
/nix/store/hdjr32qnmgqmysllvq6v5ds09mhvz5ja-gmic-3.2.0-dev/include/gmic.h:151:19: note: candidate: 'gmic_library::gmic_list<T>& gmic_library::gmic_list<T>::assign(unsigned int) [with T = char]'
  151 |     gmic_list<T>& assign(const unsigned int n);
      |                   ^~~~~~
/nix/store/hdjr32qnmgqmysllvq6v5ds09mhvz5ja-gmic-3.2.0-dev/include/gmic.h:151:19: note:   candidate expects 1 argument, 0 provided
ninja: build stopped: subcommand failed.
```

It seems like the gmic library changed its `gmic_list` API recently.

**Comment by dtschump** [comment]
Yes the API has changed, but the code of the G'MIC-Qt plug-in as well.
Did you also update the code of the plug-in ?

**Comment by NinjaTrappeur** [comment]
Yes, we bumped to the https://github.com/c-koi/gmic-qt/releases/tag/v.3.2.0 tag.

Looking at the source code, the culprit seems to be this `swap()` call here: https://github.com/c-koi/gmic-qt/blob/master/src/FilterSyncRunner.cpp#L77

There's no such function anymore in the gmic 3.2.0 codebase: https://github.com/GreycLab/gmic/blob/master/src/gmic.h#L137

That being said, I can't find the swap operation either on the 3.1.9 codebase https://github.com/GreycLab/gmic/blob/v.218/src/gmic.h#L105 . I assume I'm missing something here :thinking:

**Comment by dtschump** [comment]
Here,  `swap()` refers to `CImgList<>::swap()`, which are methods of the CImg Library (defined in file `CImg.h`). These methods exist in the library since a long time
(see: http://cimg.eu/reference/structcimg__library_1_1CImgList.html#a6c12806e432683b06fbc8919daa0a3d7).

Could it be be that CImg has not been updated from your side?

**Comment by tobiasBora** [comment]
Nix packs the latest stable version 3.2.0 ([freshly updated](https://github.com/NixOS/nixpkgs/commit/1a3f11c9f482d3b1670bc468ae36c0840c56e5b0) last week from 3.1.6).

According to hydra (NixOs continuous build tool), the package fails to build because of this error:
```
…
-- Found CImg: /nix/store/ryk6g7d1dqzma49m0h8xw5pz646wdmxz-cimg-3.2.0/include  
…
[1/7] Building CXX object CMakeFiles/gmic.dir/src/gmic_cli.cpp.o
[2/7] Building CXX object CMakeFiles/libgmic.dir/src/gmic.cpp.o
FAILED: CMakeFiles/libgmic.dir/src/gmic.cpp.o 
/nix/store/iiq295j1z4q1sxmdbrl2j8ma3l5ns4wr-gcc-wrapper-11.3.0/bin/g++ -Dcimg_display=0 -Dcimg_use_fftw3 -Dcimg_use_jpeg -Dcimg_use_magick -Dcimg_use_openexr -Dcimg_use_openmp -Dcimg_use_png -Dcimg_use_tiff -Dcimg_use_zlib -Dlibgmic_EXPORTS -isystem /build/source/src -isystem /nix/store/1jw6mz0f5gh3p3cld9frz4z1njg31ic5-graphicsmagick-1.3.39/include/GraphicsMagick -isystem /nix/store/xlp2ag333hdnwsb33sq9k5f816db9vbw-openexr-2.5.8-dev/include/OpenEXR -O3 -DNDEBUG -fPIC -Ofast -Dcimg_use_vt100 -Dgmic_is_parallel -Dcimg_use_abort -Wno-error=narrowing -fno-ipa-sra -fpermissive -Dgmic_core -fopenmp -std=gnu++11 -MD -MT CMakeFiles/libgmic.dir/src/gmic.cpp.o -MF CMakeFiles/libgmic.dir/src/gmic.cpp.o.d -o CMakeFiles/libgmic.dir/src/gmic.cpp.o -c /build/source/src/gmic.cpp
/build/source/src/gmic.cpp: In static member function 'static double gmic::mp_dollar(const char*, void*)':
/build/source/src/gmic.cpp:2352:36: error: 'is_varname' is not a member of 'cimg_library::CImg<float>::_cimg_math_parser'
 2352 |   if (!(CImg<>::_cimg_math_parser::is_varname(str) ||
      |                                    ^~~~~~~~~~
/build/source/src/gmic.cpp: In static member function 'static const char* gmic::path_rc(const char*)':
/build/source/src/gmic.cpp:2980:7: error: 'cimg_sprintf' was not declared in this scope; did you mean 'cimg_snprintf'?
 2980 |       cimg_sprintf(path_tmp,"%s/.config",_path_rc);
      |       ^~~~~~~~~~~~
      |       cimg_snprintf
```
Here are the [full logs](https://hydra.nixos.org/build/206782082/nixlog/1).

If I check in the source of the CImg library I can only see references to `cimg::is_varname` but nothing to `CImg<>::_cimg_math_parser::is_varname` (but I'm not a C++ expert so I might missed something).

**Comment by NinjaTrappeur** [comment]
^ please ignore the above message. This is the pre-bump build log. I'll paste the new one once the recently merged https://github.com/NixOS/nixpkgs/pull/211600 (containing the gmic-qt update) hits our CI.

**Comment by dtschump** [comment]
Ah I see you are using `cmake`. 
I'm not sure this is working anymore. I use `qmake` to build the plug-in.
I'll try to see if I get the same errors.

**Comment by dtschump** [comment]
OK, this doesn't work for me, for another reason:
~~~
Building for target host application: gimp
CMake Error at CMakeLists.txt:145 (find_package):
  Could not find a package configuration file provided by "Gmic" with any of
  the following names:

    GmicConfig.cmake
    gmic-config.cmake

  Add the installation prefix of "Gmic" to CMAKE_PREFIX_PATH or set
  "Gmic_DIR" to a directory containing one of the above files.  If "Gmic"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
~~~
I have no clue how to make it work, I must say :)

**Comment by NinjaTrappeur** [comment]
Ack. No worries :)

I'll migrate this to qmake tonight. Thanks for the help!

**Comment by peterhoeg** [comment]
Isn't qmake deprecated in qt6?

**Comment by jtojnar** [comment]
Yes, that’s one of the reasons I switched the Nixpkgs build to CMake in the first place. In addition to qmake having even worse developer experience than CMake.

**Comment by peterhoeg** [comment]
So we need to appeal to @dtschump to do the qmake -> cmake move then.

**Comment by dtschump** [comment]
@peterhoeg I am completely unable to do this, I have never been interested in cmake (and I honestly don't have the time to spend on it). Maybe @c-koi could help, he knows cmake surely a lot more than me.
Or anyone else interested, of course ;)

**Comment by jtojnar** [comment]
The issue is that GMic will now substitute CImg definitions with its own broken stubs when `gmic_core` preprocessor variable is not defined.

That is the case when building `gmic-qt` with `-DENABLE_SYSTEM_GMIC=on` since https://github.com/c-koi/gmic-qt/commit/d7cb84a3f079213bced8b83eecd3305eac462c0d.

Unfortunately, it is hard to tell why that decision was made on `gmic` side due to horrible engineering practices. `git blame` just points to https://github.com/GreycLab/gmic/blame/c3b2009a44bbf5afa993e4674624564c801bbbec/src/gmic.h#L81.

**Comment by dtschump** [comment]
> Unfortunately, it is hard to tell why that decision was made on gmic side due to horrible engineering practices.

Honestly, this is a very awkward way to approach the discussion. 
This decision was made for certain reasons, which you may find wrong (but I doubt you have all the cards in your hands to properly analyze the situation as a whole). In any case, it is a decision that has been made and it will probably not be reversed.
Your opinion on this issue is therefors irrelevant. I'd prefer we try to move forward rather than questioning what has already been done, and which works for other contexts than the compilation of the plug-in.

I, for one, will not participate in this kind of discussion if it goes in this direction.

**Comment by jtojnar** [comment]
Sorry, I could have probably phrased that better. I have only mentioned the practice of destroying git repository history because it is harmful to trying to debug issues like this. I was hoping that by bringing out this problem we could not repeat it in the future.

----

I tried digging deeper starting with `v.3.1.0` tag but it looks like the `#ifndef gmic_core` was [already there in 3.1.0](https://github.com/GreycLab/gmic/commit/e5846021f429ee0a4260aae52d16183fe5f77c36). Since 3.1.5 compiled successfully for us, the issue is probably something different.
